### ISSUE TITLE
大哥你可真是个人才，60M的项目，用460M的图片

### ISSUE THREAD

**Issue by lyha23** [mangohow/myblog#1]
<img width="819" alt="截屏2022-09-07 03 49 15" src="https://user-images.githubusercontent.com/75962592/188725626-3e29b17d-0a53-4f11-ab88-1496dc355da3.png">

**Comment by lyha23** [comment]
好吧，虽然我也是被图吸引来的

**Comment by mangohow** [comment]
大部分图片是wallpaper上下载的，有点大，没有做压缩。哈哈，就问你爱不爱看吧
